apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http-port
      targetPort: 8080
    - port: 50000
      name: jnlp-port
      targetPort: 50000
  selector:
    app: jenkins